import json


READING_TEXTS = [
    {
        "slug": "english-class", "level": 3, "position": 1, "title_en": "English Class", "title_pt": "Aula de inglês", "category": "Study", "icon": "bi-easel2",
        "body_en": "I really enjoy my English class. Our teacher is enthusiastic and makes learning fun. Each lesson is different, so the class always feels interesting. We often work in pairs because speaking with another student helps us feel more confident.\n\nWe do many activities, such as group discussions, role-playing, listening games, and short presentations. We also read texts and articles to improve our vocabulary and comprehension. My favorite activity is watching a short scene from a movie and discussing what happened. It helps me understand how English is used in real-life situations.",
        "body_pt": "Eu realmente gosto da minha aula de inglês. Nossa professora é entusiasmada e torna o aprendizado divertido. Cada aula é diferente, por isso a turma permanece interessante. Frequentemente trabalhamos em duplas porque falar com outro aluno nos ajuda a ter mais confiança.\n\nFazemos muitas atividades, como discussões em grupo, dramatizações, jogos de escuta e pequenas apresentações. Também lemos textos e artigos para melhorar o vocabulário e a compreensão. Minha atividade favorita é assistir a uma cena curta de um filme e conversar sobre o que aconteceu. Isso me ajuda a entender como o inglês é usado em situações reais.",
        "vocab": [("enthusiastic", "entusiasmado"), ("confident", "confiante"), ("role-playing", "dramatização"), ("comprehension", "compreensão"), ("real-life situations", "situações da vida real")],
        "questions": [("Why do the students work in pairs?", "Por que os alunos trabalham em duplas?", ["To become more confident", "To finish class early", "To avoid speaking", "To watch television"], "To become more confident"), ("What is the narrator's favorite activity?", "Qual é a atividade favorita do narrador?", ["Watching and discussing a movie scene", "Taking a grammar test", "Writing long reports", "Leaving the classroom"], "Watching and discussing a movie scene")],
    },
    {
        "slug": "my-busy-week", "level": 3, "position": 2, "title_en": "My Busy Week", "title_pt": "Minha semana corrida", "category": "Routine", "icon": "bi-calendar-week",
        "body_en": "My week is busy, but I try to organize my time carefully. From Monday to Friday, I get up early, have breakfast, and go to work. I usually check my tasks before starting the day. At lunchtime, I take a short break and sometimes study new English words.\n\nIn the evening, I study Python or practice English on my computer. I do not study for many hours without stopping. I divide the work into small sessions and take short breaks. On Saturday, I review what I learned. Sunday is quieter, so I rest, read, and prepare for the next week.",
        "body_pt": "Minha semana é corrida, mas tento organizar meu tempo com cuidado. De segunda a sexta, levanto cedo, tomo café e vou trabalhar. Geralmente verifico minhas tarefas antes de começar o dia. Na hora do almoço, faço uma pausa curta e às vezes estudo palavras novas em inglês.\n\nÀ noite, estudo Python ou pratico inglês no computador. Não estudo durante muitas horas sem parar. Divido o trabalho em pequenas sessões e faço pausas curtas. No sábado, reviso o que aprendi. O domingo é mais tranquilo, então descanso, leio e me preparo para a próxima semana.",
        "vocab": [("carefully", "cuidadosamente"), ("task", "tarefa"), ("break", "pausa"), ("divide", "dividir"), ("prepare", "preparar")],
        "questions": [("What does the narrator do at lunchtime?", "O que o narrador faz na hora do almoço?", ["Takes a short break", "Goes to bed", "Starts the weekend", "Runs a meeting"], "Takes a short break"), ("Why are study sessions divided?", "Por que as sessões de estudo são divididas?", ["To study in manageable periods", "To avoid learning", "To work all night", "To cancel the plan"], "To study in manageable periods")],
    },
    {
        "slug": "english-with-technology", "level": 3, "position": 3, "title_en": "Learning English with Technology", "title_pt": "Aprendendo inglês com tecnologia", "category": "Technology", "icon": "bi-tablet",
        "body_en": "Technology gives learners many ways to practice English. A phone can play audio, show subtitles, save flashcards, and connect students with people from other countries. A computer is useful for writing, reading documentation, and joining online classes.\n\nHowever, using many applications does not automatically produce good results. A learner still needs a clear routine and active practice. I listen to a short recording, repeat each sentence, and then explain the main idea in my own words. When I make a mistake, I save the difficult expression and review it later. Technology is most useful when it supports a consistent learning method.",
        "body_pt": "A tecnologia oferece muitas maneiras de praticar inglês. Um telefone pode reproduzir áudio, mostrar legendas, salvar cartões de memorização e conectar alunos a pessoas de outros países. Um computador é útil para escrever, ler documentação e participar de aulas on-line.\n\nEntretanto, usar muitos aplicativos não produz bons resultados automaticamente. O aluno ainda precisa de uma rotina clara e prática ativa. Eu ouço uma gravação curta, repito cada frase e depois explico a ideia principal com minhas próprias palavras. Quando cometo um erro, salvo a expressão difícil e a reviso mais tarde. A tecnologia é mais útil quando apoia um método consistente de aprendizagem.",
        "vocab": [("subtitle", "legenda"), ("flashcard", "cartão de memorização"), ("automatically", "automaticamente"), ("in my own words", "com minhas próprias palavras"), ("consistent", "consistente")],
        "questions": [("What does the learner do after listening?", "O que o aluno faz depois de ouvir?", ["Repeats and explains the idea", "Deletes the recording", "Changes the language", "Stops studying"], "Repeats and explains the idea"), ("When is technology most useful?", "Quando a tecnologia é mais útil?", ["When it supports a consistent method", "When there are many apps", "When practice is passive", "When mistakes are ignored"], "When it supports a consistent method")],
    },
    {
        "slug": "first-python-project", "level": 3, "position": 4, "title_en": "My First Python Project", "title_pt": "Meu primeiro projeto Python", "category": "Python", "icon": "bi-filetype-py",
        "body_en": "My first Python project was a small expense tracker. The user could enter a description, a category, and an amount. The program stored each record in a list and calculated the total. At first, all the code was in one file because I wanted to understand the basic logic.\n\nAfter the program worked, I separated the code into functions. One function validated the amount, another saved the data, and a third displayed the report. I also added error messages for invalid input. The project was simple, but it taught me an important lesson: clean structure makes a program easier to test, explain, and improve.",
        "body_pt": "Meu primeiro projeto Python foi um pequeno controle de despesas. O usuário podia informar uma descrição, uma categoria e um valor. O programa armazenava cada registro em uma lista e calculava o total. No início, todo o código estava em um arquivo porque eu queria entender a lógica básica.\n\nDepois que o programa funcionou, separei o código em funções. Uma função validava o valor, outra salvava os dados e uma terceira exibia o relatório. Também acrescentei mensagens de erro para entradas inválidas. O projeto era simples, mas me ensinou uma lição importante: uma estrutura organizada torna o programa mais fácil de testar, explicar e melhorar.",
        "vocab": [("expense tracker", "controle de despesas"), ("amount", "valor"), ("record", "registro"), ("invalid input", "entrada inválida"), ("clean structure", "estrutura organizada")],
        "questions": [("What did the program calculate?", "O que o programa calculava?", ["The total expenses", "The user's age", "The internet speed", "The number of files"], "The total expenses"), ("Why did the narrator create functions?", "Por que o narrador criou funções?", ["To organize responsibilities", "To remove all logic", "To make one long file", "To avoid testing"], "To organize responsibilities")],
    },
    {
        "slug": "bug-that-taught-me", "level": 3, "position": 5, "title_en": "The Bug That Taught Me", "title_pt": "O erro que me ensinou", "category": "Problem Solving", "icon": "bi-bug",
        "body_en": "One evening, my Flask application stopped saving new users. The registration page opened normally, but every submission returned an internal server error. I first checked the form and the route, yet I could not see the problem. Then I read the complete traceback instead of looking only at the last line.\n\nThe message showed that the database expected a field that my SQL statement did not provide. I had changed the schema but forgotten to update the insert query. After correcting the query, I wrote a test that created a new user. The bug reminded me that an error message is evidence, not an enemy. Careful reading often saves more time than random changes.",
        "body_pt": "Certa noite, minha aplicação Flask parou de salvar novos usuários. A página de cadastro abria normalmente, mas cada envio retornava um erro interno do servidor. Primeiro verifiquei o formulário e a rota, porém não encontrei o problema. Então li todo o traceback em vez de olhar apenas a última linha.\n\nA mensagem mostrou que o banco esperava um campo que minha instrução SQL não fornecia. Eu havia alterado o esquema, mas esquecido de atualizar a consulta de inserção. Depois de corrigir a consulta, escrevi um teste que criava um novo usuário. O erro me lembrou que uma mensagem de erro é uma evidência, não uma inimiga. Ler com atenção geralmente economiza mais tempo do que fazer alterações aleatórias.",
        "vocab": [("submission", "envio"), ("traceback", "rastreamento do erro"), ("expected", "esperava"), ("insert query", "consulta de inserção"), ("evidence", "evidência")],
        "questions": [("What caused the error?", "O que causou o erro?", ["A missing field in the insert query", "A broken monitor", "An incorrect password", "A slow browser"], "A missing field in the insert query"), ("What lesson did the narrator learn?", "Qual lição o narrador aprendeu?", ["Read errors carefully", "Change code randomly", "Avoid automated tests", "Ignore the traceback"], "Read errors carefully")],
    },
    {
        "slug": "remote-work-routine", "level": 3, "position": 6, "title_en": "A Productive Remote Work Routine", "title_pt": "Uma rotina produtiva de trabalho remoto", "category": "Work", "icon": "bi-house-laptop",
        "body_en": "Working from home can be comfortable, but it requires discipline. I start at the same time every morning and review my priorities before opening email. I keep my desk organized and turn off unnecessary notifications. During focused work, I complete one important task before moving to another.\n\nCommunication is also essential. I write clear updates so my teammates know what I finished and where I need help. In online meetings, I take notes and confirm the next action. At the end of the day, I update the task board and close my work applications. This routine creates a clear boundary between work time and personal time.",
        "body_pt": "Trabalhar em casa pode ser confortável, mas exige disciplina. Começo no mesmo horário todas as manhãs e reviso minhas prioridades antes de abrir o e-mail. Mantenho minha mesa organizada e desativo notificações desnecessárias. Durante o trabalho concentrado, concluo uma tarefa importante antes de passar para outra.\n\nA comunicação também é essencial. Escrevo atualizações claras para que meus colegas saibam o que concluí e onde preciso de ajuda. Nas reuniões on-line, faço anotações e confirmo a próxima ação. No fim do dia, atualizo o quadro de tarefas e fecho os aplicativos de trabalho. Essa rotina cria um limite claro entre o horário de trabalho e o tempo pessoal.",
        "vocab": [("priority", "prioridade"), ("notification", "notificação"), ("focused work", "trabalho concentrado"), ("teammate", "colega de equipe"), ("boundary", "limite")],
        "questions": [("What happens before email is opened?", "O que acontece antes de abrir o e-mail?", ["Priorities are reviewed", "Work applications are closed", "Lunch is prepared", "The meeting ends"], "Priorities are reviewed"), ("Why are clear updates important?", "Por que atualizações claras são importantes?", ["They keep teammates informed", "They replace all meetings", "They increase notifications", "They hide problems"], "They keep teammates informed")],
    },
    {
        "slug": "life-abroad", "level": 3, "position": 7, "title_en": "A New Life Abroad", "title_pt": "Uma nova vida no exterior", "category": "Travel", "icon": "bi-globe-americas",
        "body_en": "Moving to another country is exciting, but the first weeks can be challenging. Simple activities, such as taking a bus or buying groceries, may require new words and unfamiliar customs. An international student must learn how the city works while also attending classes and completing assignments.\n\nThe experience becomes easier when the student asks questions and accepts small mistakes. Joining a study group is a good way to meet people and practice the local language. Over time, strange places become familiar and daily tasks require less effort. Living abroad does more than teach a language; it also develops independence, patience, and respect for different cultures.",
        "body_pt": "Mudar para outro país é empolgante, mas as primeiras semanas podem ser desafiadoras. Atividades simples, como pegar um ônibus ou comprar mantimentos, podem exigir palavras novas e costumes desconhecidos. Um estudante internacional precisa aprender como a cidade funciona enquanto frequenta aulas e conclui trabalhos.\n\nA experiência fica mais fácil quando o estudante faz perguntas e aceita pequenos erros. Participar de um grupo de estudos é uma boa maneira de conhecer pessoas e praticar o idioma local. Com o tempo, lugares estranhos tornam-se familiares e as tarefas diárias exigem menos esforço. Morar no exterior faz mais do que ensinar um idioma; também desenvolve independência, paciência e respeito por culturas diferentes.",
        "vocab": [("abroad", "no exterior"), ("groceries", "mantimentos"), ("unfamiliar", "desconhecido"), ("assignment", "trabalho escolar"), ("independence", "independência")],
        "questions": [("What can help a student meet people?", "O que pode ajudar um estudante a conhecer pessoas?", ["Joining a study group", "Avoiding questions", "Staying alone", "Missing classes"], "Joining a study group"), ("What does living abroad develop?", "O que morar no exterior desenvolve?", ["Independence and patience", "Only grammar", "Less respect", "Fewer responsibilities"], "Independence and patience")],
    },
    {
        "slug": "healthy-learning-habits", "level": 3, "position": 8, "title_en": "Healthy Learning Habits", "title_pt": "Hábitos saudáveis de aprendizagem", "category": "Study", "icon": "bi-heart-pulse",
        "body_en": "Learning effectively is not only about studying longer. The brain needs attention, repetition, rest, and time to organize new information. A short daily session can be more useful than one exhausting session at the end of the week. Active recall is especially powerful: close the book and try to explain the idea without looking.\n\nSleep and movement also influence memory. After studying, a short walk can reduce stress and help the mind process the lesson. Before going to bed, I review a few difficult cards instead of starting a completely new topic. The next day, I test myself again. Progress may feel slow, but consistent practice produces strong results.",
        "body_pt": "Aprender com eficiência não significa apenas estudar por mais tempo. O cérebro precisa de atenção, repetição, descanso e tempo para organizar informações novas. Uma sessão curta todos os dias pode ser mais útil do que uma sessão cansativa no fim da semana. A recordação ativa é especialmente poderosa: feche o livro e tente explicar a ideia sem olhar.\n\nO sono e o movimento também influenciam a memória. Depois de estudar, uma caminhada curta pode reduzir o estresse e ajudar a mente a processar a aula. Antes de dormir, reviso alguns cartões difíceis em vez de começar um assunto completamente novo. No dia seguinte, testo novamente meu conhecimento. O progresso pode parecer lento, mas a prática consistente produz resultados sólidos.",
        "vocab": [("effectively", "com eficiência"), ("exhausting", "cansativo"), ("active recall", "recordação ativa"), ("influence", "influenciar"), ("consistent", "consistente")],
        "questions": [("What is active recall?", "O que é recordação ativa?", ["Explaining without looking", "Reading without stopping", "Copying every page", "Skipping review"], "Explaining without looking"), ("What can a short walk do?", "O que uma caminhada curta pode fazer?", ["Reduce stress", "Erase the lesson", "Replace sleep", "Create more work"], "Reduce stress")],
    },
    {
        "slug": "software-demo", "level": 4, "position": 1, "title_en": "Presenting a Software Project", "title_pt": "Apresentando um projeto de software", "category": "Professional English", "icon": "bi-display",
        "body_en": "A strong software presentation begins with the user's problem, not with a list of technologies. First, explain who needs the solution and what difficulty they face. Then demonstrate the main workflow with realistic data. The audience should understand the value of the product before hearing details about the architecture.\n\nDuring the technical section, describe the most important decisions and their trade-offs. Explain how the application validates data, protects access, and handles errors. Avoid reading every line on the screen. Instead, guide the audience through one clear story: problem, solution, evidence, and next steps. Finish by inviting questions and recording useful feedback for the next version.",
        "body_pt": "Uma boa apresentação de software começa com o problema do usuário, não com uma lista de tecnologias. Primeiro, explique quem precisa da solução e qual dificuldade essa pessoa enfrenta. Depois, demonstre o fluxo principal com dados realistas. O público deve compreender o valor do produto antes de ouvir detalhes sobre a arquitetura.\n\nNa parte técnica, descreva as decisões mais importantes e suas compensações. Explique como a aplicação valida dados, protege o acesso e trata erros. Evite ler cada linha da tela. Em vez disso, conduza o público por uma história clara: problema, solução, evidência e próximos passos. Termine convidando perguntas e registrando retornos úteis para a próxima versão.",
        "vocab": [("workflow", "fluxo de trabalho"), ("realistic data", "dados realistas"), ("trade-off", "compensação entre escolhas"), ("handle errors", "tratar erros"), ("feedback", "retorno / opinião")],
        "questions": [("What should the presentation begin with?", "Com o que a apresentação deve começar?", ["The user's problem", "A long technology list", "Every line of code", "The final price only"], "The user's problem"), ("What story should guide the audience?", "Qual história deve orientar o público?", ["Problem, solution, evidence, next steps", "Code, code, code, code", "Price, color, logo, exit", "Meeting, break, lunch, email"], "Problem, solution, evidence, next steps")],
    },
    {
        "slug": "technical-interview", "level": 4, "position": 2, "title_en": "The Technical Interview", "title_pt": "A entrevista técnica", "category": "Career", "icon": "bi-person-workspace",
        "body_en": "In a technical interview, knowing the answer is useful, but explaining your reasoning is often more important. When you receive a problem, confirm the requirements and ask about unclear details. Describe a simple solution first, then discuss how you could improve its performance, readability, or security.\n\nIf you do not know something, be honest and explain how you would investigate it. You can mention documentation, tests, logs, or a small experiment. When discussing past projects, use a clear structure: situation, task, action, and result. Specific examples show more than general claims. A good interview is not a memory contest; it is evidence of how you communicate and solve problems.",
        "body_pt": "Em uma entrevista técnica, saber a resposta é útil, mas explicar seu raciocínio costuma ser ainda mais importante. Ao receber um problema, confirme os requisitos e pergunte sobre detalhes pouco claros. Descreva primeiro uma solução simples e depois explique como poderia melhorar o desempenho, a legibilidade ou a segurança.\n\nSe você não souber algo, seja honesto e explique como investigaria. Você pode mencionar documentação, testes, registros ou um pequeno experimento. Ao falar de projetos anteriores, use uma estrutura clara: situação, tarefa, ação e resultado. Exemplos específicos demonstram mais do que afirmações gerais. Uma boa entrevista não é uma competição de memória; é uma evidência de como você se comunica e resolve problemas.",
        "vocab": [("reasoning", "raciocínio"), ("requirement", "requisito"), ("readability", "legibilidade"), ("investigate", "investigar"), ("specific example", "exemplo específico")],
        "questions": [("What should you do with unclear details?", "O que fazer com detalhes pouco claros?", ["Ask questions", "Ignore them", "Invent requirements", "End the interview"], "Ask questions"), ("What should you explain when you do not know?", "O que explicar quando você não sabe?", ["How you would investigate", "Why the question is bad", "That tests are useless", "Nothing"], "How you would investigate")],
    },
    {
        "slug": "data-to-decision", "level": 4, "position": 3, "title_en": "From Data to Decision", "title_pt": "Dos dados à decisão", "category": "Data Analysis", "icon": "bi-graph-up-arrow",
        "body_en": "A dashboard is valuable only when it helps someone make a better decision. Before creating charts, an analyst should define the business question, the audience, and the action that may follow. A beautiful visualization cannot repair incomplete data or an unclear objective.\n\nThe analyst must check missing values, duplicates, unusual records, and inconsistent definitions. After cleaning the data, each metric needs a clear formula and context. For example, revenue can increase while profit decreases, so one number rarely tells the complete story. A professional conclusion separates facts from assumptions, explains limitations, and recommends the next step. The goal is not to impress people with charts; it is to reduce uncertainty.",
        "body_pt": "Um painel só é valioso quando ajuda alguém a tomar uma decisão melhor. Antes de criar gráficos, o analista deve definir a pergunta de negócio, o público e a ação que poderá ocorrer. Uma visualização bonita não corrige dados incompletos nem um objetivo pouco claro.\n\nO analista precisa verificar valores ausentes, duplicidades, registros incomuns e definições inconsistentes. Depois de limpar os dados, cada métrica precisa de fórmula e contexto claros. Por exemplo, a receita pode aumentar enquanto o lucro diminui, portanto um único número raramente conta toda a história. Uma conclusão profissional separa fatos de suposições, explica limitações e recomenda o próximo passo. O objetivo não é impressionar com gráficos, mas reduzir a incerteza.",
        "vocab": [("audience", "público"), ("missing value", "valor ausente"), ("duplicate", "duplicidade"), ("assumption", "suposição"), ("uncertainty", "incerteza")],
        "questions": [("What comes before creating charts?", "O que vem antes de criar gráficos?", ["Defining the business question", "Choosing bright colors", "Printing the dashboard", "Deleting all records"], "Defining the business question"), ("What is the final goal?", "Qual é o objetivo final?", ["Reduce uncertainty", "Use more charts", "Hide limitations", "Show one number"], "Reduce uncertainty")],
    },
    {
        "slug": "reliable-api-integration", "level": 4, "position": 4, "title_en": "Building a Reliable API Integration", "title_pt": "Construindo uma integração de API confiável", "category": "APIs", "icon": "bi-braces",
        "body_en": "An API integration connects systems that may fail in different ways. The remote service can be slow, unavailable, or return unexpected data. For this reason, a reliable client validates the request before sending it and validates the response before using it. Timeouts prevent the application from waiting forever.\n\nRetries can help with temporary failures, but they must be limited and used carefully. Repeating a payment request, for example, may create a duplicate transaction unless the operation is idempotent. Logs should record useful technical context without exposing passwords or personal data. Good integration code also separates transport, validation, and business rules. This structure makes failures easier to test and diagnose.",
        "body_pt": "Uma integração de API conecta sistemas que podem falhar de maneiras diferentes. O serviço remoto pode ficar lento, indisponível ou retornar dados inesperados. Por isso, um cliente confiável valida a requisição antes de enviá-la e valida a resposta antes de utilizá-la. Limites de tempo impedem que a aplicação espere para sempre.\n\nNovas tentativas podem ajudar em falhas temporárias, mas precisam ser limitadas e usadas com cuidado. Repetir uma solicitação de pagamento, por exemplo, pode criar uma transação duplicada, a menos que a operação seja idempotente. Os registros devem guardar contexto técnico útil sem expor senhas ou dados pessoais. Um bom código de integração também separa transporte, validação e regras de negócio. Essa estrutura torna as falhas mais fáceis de testar e diagnosticar.",
        "vocab": [("timeout", "limite de tempo"), ("retry", "nova tentativa"), ("duplicate transaction", "transação duplicada"), ("idempotent", "idempotente"), ("diagnose", "diagnosticar")],
        "questions": [("What prevents endless waiting?", "O que impede uma espera infinita?", ["A timeout", "A password", "A duplicate", "A color theme"], "A timeout"), ("Why can payment retries be dangerous?", "Por que repetir pagamentos pode ser perigoso?", ["They may create duplicates", "They improve validation", "They hide logs", "They reduce data"], "They may create duplicates")],
    },
    {
        "slug": "security-by-design", "level": 4, "position": 5, "title_en": "Security by Design", "title_pt": "Segurança desde o projeto", "category": "Security", "icon": "bi-shield-lock",
        "body_en": "Security is not a feature that should be added only after an application is finished. It begins with understanding what data the system stores, who can access it, and what could go wrong. The application should collect only necessary information and give each user the minimum permissions required for a task.\n\nPasswords must be stored as strong hashes, uploads must be validated, and database queries must be parameterized. Sensitive values belong in protected configuration, not in source code. Errors shown to users should be helpful without revealing internal details. Regular updates, backups, and tests reduce risk, but no system is perfectly secure. Good security combines prevention, detection, response, and continuous improvement.",
        "body_pt": "Segurança não é uma funcionalidade que deve ser acrescentada somente depois que uma aplicação estiver pronta. Ela começa com a compreensão de quais dados o sistema armazena, quem pode acessá-los e o que pode dar errado. A aplicação deve coletar apenas informações necessárias e conceder a cada usuário as permissões mínimas exigidas por uma tarefa.\n\nAs senhas devem ser armazenadas como hashes fortes, os uploads precisam ser validados e as consultas ao banco devem ser parametrizadas. Valores sensíveis pertencem a configurações protegidas, não ao código-fonte. Os erros exibidos ao usuário devem ajudar sem revelar detalhes internos. Atualizações, backups e testes regulares reduzem o risco, mas nenhum sistema é perfeitamente seguro. Uma boa segurança combina prevenção, detecção, resposta e melhoria contínua.",
        "vocab": [("minimum permission", "permissão mínima"), ("hash", "resumo criptográfico"), ("parameterized query", "consulta parametrizada"), ("sensitive value", "valor sensível"), ("continuous improvement", "melhoria contínua")],
        "questions": [("How much data should an app collect?", "Quantos dados um aplicativo deve coletar?", ["Only what is necessary", "Everything possible", "No validation data", "Only passwords"], "Only what is necessary"), ("Where should sensitive values be kept?", "Onde valores sensíveis devem ficar?", ["In protected configuration", "In public source code", "Inside error messages", "In filenames"], "In protected configuration")],
    },
    {
        "slug": "constructive-code-review", "level": 4, "position": 6, "title_en": "A Constructive Code Review", "title_pt": "Uma revisão de código construtiva", "category": "Teamwork", "icon": "bi-git",
        "body_en": "Code review is both a quality process and a conversation between professionals. A reviewer should understand the purpose of the change before commenting on individual lines. Small pull requests with a clear description are easier to evaluate than large changes that mix unrelated goals.\n\nUseful comments explain the risk or principle behind a suggestion. Instead of writing “This is wrong,” a reviewer can ask, “Could this value be empty?” or suggest a test for the edge case. Authors should not treat every question as criticism. They can explain their decision, accept the suggestion, or propose another solution. Respectful review spreads knowledge, finds defects, and helps the team maintain consistent standards.",
        "body_pt": "A revisão de código é ao mesmo tempo um processo de qualidade e uma conversa entre profissionais. O revisor deve compreender a finalidade da alteração antes de comentar linhas individuais. Pull requests pequenas, com descrição clara, são mais fáceis de avaliar do que grandes mudanças que misturam objetivos sem relação.\n\nComentários úteis explicam o risco ou o princípio por trás de uma sugestão. Em vez de escrever “Isto está errado”, o revisor pode perguntar “Este valor poderia estar vazio?” ou sugerir um teste para o caso extremo. Os autores não devem interpretar toda pergunta como crítica. Eles podem explicar a decisão, aceitar a sugestão ou propor outra solução. Uma revisão respeitosa compartilha conhecimento, encontra defeitos e ajuda a equipe a manter padrões consistentes.",
        "vocab": [("purpose", "finalidade"), ("unrelated", "sem relação"), ("edge case", "caso extremo"), ("criticism", "crítica"), ("consistent standard", "padrão consistente")],
        "questions": [("What should a reviewer understand first?", "O que o revisor deve entender primeiro?", ["The purpose of the change", "The author's age", "The final filename", "The office location"], "The purpose of the change"), ("What do respectful reviews spread?", "O que revisões respeitosas disseminam?", ["Knowledge", "Personal criticism", "Unrelated changes", "Passwords"], "Knowledge")],
    },
    {
        "slug": "ai-and-automation", "level": 4, "position": 7, "title_en": "AI and the Future of Automation", "title_pt": "IA e o futuro da automação", "category": "Artificial Intelligence", "icon": "bi-robot",
        "body_en": "Artificial intelligence can automate parts of a process, but a useful solution begins with a real problem. A team should map the current workflow, identify repeated decisions, and measure the cost of errors. Some steps can be handled by fixed rules, while others may benefit from a model that interprets text, images, or patterns.\n\nHuman review remains important when decisions affect money, rights, safety, or reputation. The system should record what happened, allow corrections, and make uncertainty visible. Automation also needs monitoring because data and user behavior change over time. The best projects do not use AI simply because it is popular. They combine clear goals, reliable data, thoughtful design, and responsible human oversight.",
        "body_pt": "A inteligência artificial pode automatizar partes de um processo, mas uma solução útil começa com um problema real. A equipe deve mapear o fluxo atual, identificar decisões repetidas e medir o custo dos erros. Algumas etapas podem ser executadas por regras fixas, enquanto outras podem se beneficiar de um modelo que interpreta textos, imagens ou padrões.\n\nA revisão humana continua importante quando as decisões afetam dinheiro, direitos, segurança ou reputação. O sistema deve registrar o que aconteceu, permitir correções e tornar a incerteza visível. A automação também precisa de monitoramento porque os dados e o comportamento dos usuários mudam com o tempo. Os melhores projetos não usam IA apenas porque ela está popular. Eles combinam objetivos claros, dados confiáveis, projeto cuidadoso e supervisão humana responsável.",
        "vocab": [("workflow", "fluxo de trabalho"), ("fixed rule", "regra fixa"), ("human oversight", "supervisão humana"), ("uncertainty", "incerteza"), ("monitoring", "monitoramento")],
        "questions": [("What should an AI solution begin with?", "Com o que uma solução de IA deve começar?", ["A real problem", "A popular model", "A large logo", "A random workflow"], "A real problem"), ("When is human review especially important?", "Quando a revisão humana é especialmente importante?", ["When decisions have serious impact", "Only when colors change", "When there is no data", "Only during installation"], "When decisions have serious impact")],
    },
]


def seed_reading_content(db):
    for item in READING_TEXTS:
        db.execute(
            """
            INSERT INTO reading_texts
                (slug, level, position, title_en, title_pt, category, icon, body_en, body_pt, vocabulary, questions)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(slug) DO UPDATE SET
                level=excluded.level, position=excluded.position, title_en=excluded.title_en,
                title_pt=excluded.title_pt, category=excluded.category, icon=excluded.icon,
                body_en=excluded.body_en, body_pt=excluded.body_pt,
                vocabulary=excluded.vocabulary, questions=excluded.questions
            """,
            (item["slug"], item["level"], item["position"], item["title_en"], item["title_pt"],
             item["category"], item["icon"], item["body_en"], item["body_pt"],
             json.dumps(item["vocab"], ensure_ascii=False), json.dumps([
                 {"question_en": q[0], "question_pt": q[1], "options": q[2], "answer": q[3]}
                 for q in item["questions"]
             ], ensure_ascii=False)),
        )
